### PR TITLE
add post and comment form width restriction

### PR DESCRIPTION
**Pull request by Djones4822**
this seems to work in my testing, let me know

### CODE REVIEW

**Comment by Djones4822** [comment]
I noticed that comments don't have their background limited, just the actual text width, is that what you wanted? 

image

**Comment by soundjester** [comment]
I believe that this change is addressed in the current code for Lemmy v0.18:

https://github.com/soundjester/lemmy_monkey/blob/45fb495aa1e18af5bc299e9c3e756770f204940b/old.reddit.compact.user.js#L190

Regarding comment background width, the desired behavior is to extend with the screen.  It looks pretty good in v0.18.

image

**Comment by Djones4822** [comment]
I saw there was some stlying but it doesn't work on lemmy.world - but they haven't updated to 18 since it doesn't have captcha support

**Comment by soundjester** [comment]
Ah.  Does v0.17 have captcha?  I didn't think it did, but I wasn't paying close attention.

I've had to ditch development for v0.17 styles.  I just can't support both at the moment.  There is a v0.17 branch though if you want to pull against that.  But the main scripts are all v0.18 now.

**Comment by DogmaDragon** [comment]
> Ah. Does v0.17 have captcha? I didn't think it did, but I wasn't paying close attention.
> 
> I've had to ditch development for v0.17 styles. I just can't support both at the moment. There is a v0.17 branch though if you want to pull against that. But the main scripts are all v0.18 now.

Very basic one, but I think they are planning to add mCaptcha. Sorry for off topic.

**Comment by soundjester** [comment]
This cannot be merged into the current Lemmy v0.18 version of the script.

**Pull request closed without merging**
